home-assistant:
  deploymentStrategy:
    type: Recreate
  timezone: "America/Chicago"
  image:
    tag: 0.118.4
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hosts:
      - hass.northstarcc.club
    tls:
      - secretName: hass-tls
        hosts:
          - hass.northstarcc.club
  vscode:
    enabled: true
    ingress:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      path: /
      hosts:
        - vshass.northstarcc.club
      tls: 
        - secretName: vshass.northstarcc.club
          hosts:
            - vshass.northstarcc.club
