home-assistant:
  deploymentStrategy:
    type: Recreate
  timezone: "America/Chicago"
  image:
    tag: 0.118.2
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hosts:
      - hass.northstarcc.club
    tls:
      - secretName: hass-tls
        hosts:
          - hass.northstarcc.club
  vscode:
    enabled: true
    ingress:
      enabled: true
    hosts:
      - vshass.nortstarcc.club
    tls:
      - secretName: vshass-tls
      hosts:
        - vshass.northstarcc.club
